### ISSUE TITLE
Wont load my stream

### ISSUE THREAD

**Issue by silverskater12Ineedhelp** [knifftech/FullStream#3] opened 2015-09-10 18:16 UTC
I try to watch streams on fullstream but it says its loading and just stops at where it says twitch and never plays PLS HALP!

**Comment by knifftech** [comment] 2015-09-10 21:40
Hi, can you provide a screenshot?

**Comment by knifftech** [comment] 2015-09-10 22:43
I just did a patch, hopefully that fixed it.
If not, let me know.

**Comment by silverskater12Ineedhelp** [comment] 2015-09-15 17:22
it didn't workthx for trying

**Comment by knifftech** [comment] 2015-09-15 17:26
Can you explain more about what the issue is?
Maybe provide a screenshot?

**Comment by knifftech** [comment] 2015-09-24 20:09
No reply in over a week, closing the issue.

**Closed by knifftech** 2015-09-24 20:09 UTC
